services:
  postgres:
    container_name: pg-demo17
    image: postgres:17
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: pgdemo
      POSTGRES_USER: pg-demo17
      POSTGRES_PASSWORD: pg!!!
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    ports:
      - "5432:5432"
    volumes:
      - pg-demo-data:/var/lib/postgresql/data
  mysql:
    image: mysql:8.4
    container_name: my-demo84
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root!!!
    # --default-authentication-plugin=mysql_native_passwordhはMySQL 8.4以降では廃止になったので不要！
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci','--default-time-zone=+09:00',]
    ports:
      - "3306:3306"
    volumes:
      - my-demo-data:/var/lib/mysql
# 名前付きボリュームの定義
volumes:
  pg-demo-data:
    name: pg-demo-data
  my-demo-data:
    name: my-demo-data
  