create table if not exists company
(
    id         uuid                     default gen_random_uuid() not null
        primary key,
    created_at timestamp with time zone default now()             not null,
    name       text                                               not null
);

create table if not exists organization
(
    id         uuid                     default gen_random_uuid() not null
        primary key,
    created_at timestamp with time zone default now()             not null,
    name       text
);

create index if not exists organization_created_at_index
    on organization (created_at);


create table if not exists organization_chart
(
    id                     bigint generated by default as identity (maxvalue 2147483647)
        constraint id
            primary key,
    company_id             uuid not null
        constraint organization_chart_company_id_fk
            references company,
    parent_organization_id uuid not null
        constraint organization_chart_organization_id_fk_2
            references organization,
    organization_id        uuid not null
        constraint organization_chart_organization_id_fk
            references organization
);

create table if not exists user
(
    id         uuid                     default gen_random_uuid() not null
        primary key,
    created_at timestamp with time zone default now()             not null,
    name       text                                               not null,
);

create table if not exists staff
(
    id         uuid                     default gen_random_uuid() not null
        primary key,
    created_at timestamp with time zone default now()             not null,
    user_id    uuid not null
        constraint staff_user_id_fk
            references user,
    organization_id uuid not null
        constraint staff_organization_id_fk
            references organization
);

create table if not exists admin
(
    id         uuid                     default gen_random_uuid() not null
        primary key,
    created_at timestamp with time zone default now()             not null,
    user_id    uuid not null
        constraint admin_user_id_fk
            references user,
);

create table if not exists rls_key
(
    id         uuid                     default gen_random_uuid() not null
        primary key,
    created_at timestamp with time zone default now()             not null,
    key        uuid                                               not null,
)

create table if not exists rls_company_group
(
    id         uuid                     default gen_random_uuid() not null
        primary key,
    created_at timestamp with time zone default now()             not null,
    rls_key_id uuid not null
        constraint rls_company_group_rls_key_id_fk
            references rls_key,
    company_id uuid not null
        constraint rls_company_group_company_id_fk
            references company
);